# Generated by Django 3.2.22 on 2023-10-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=15, unique=True)),
                ('host', models.CharField(default='', max_length=50, unique=True)),
                ('guest_can_Pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.IntegerField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
